spring:
  application:
    name: webflux-spring
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/bookstore
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml